#!/bin/bash
# 设置量化交易自动运行定时任务

echo "============================================================"
echo "设置 A 股量化交易自动运行"
echo "============================================================"

# 获取当前用户
USER=$(whoami)
PROJECT_DIR="/root/.openclaw/workspace/quant-trading"
LOG_DIR="$PROJECT_DIR/logs"
PYTHON_CMD="python3"

# 确保日志目录存在
mkdir -p $LOG_DIR

echo ""
echo "项目目录：$PROJECT_DIR"
echo "日志目录：$LOG_DIR"
echo ""

# 备份现有 crontab
echo "备份现有 crontab..."
crontab -l > /tmp/cron_backup_$(date +%Y%m%d_%H%M%S).txt 2>/dev/null || echo "无现有 crontab"

# 创建新的 crontab 任务
cat > /tmp/quant_cron.txt << 'EOF'
# A 股量化交易自动运行任务
# Generated by Quant Trading System

# 09:20 - 启动早盘监控 (集合竞价后)
20 9 * * 1-5 cd /root/.openclaw/workspace/quant-trading && python3 auto_trading.py --once >> logs/daily_$(date +\%Y\%m\%d).log 2>&1

# 09:35 - 早盘第一次扫描
35 9 * * 1-5 cd /root/.openclaw/workspace/quant-trading && python3 auto_trading.py --once >> logs/daily_$(date +\%Y\%m\%d).log 2>&1

# 10:00 - 早盘第二次扫描
0 10 * * 1-5 cd /root/.openclaw/workspace/quant-trading && python3 auto_trading.py --once >> logs/daily_$(date +\%Y\%m\%d).log 2>&1

# 10:30 - 早盘第三次扫描
30 10 * * 1-5 cd /root/.openclaw/workspace/quant-trading && python3 auto_trading.py --once >> logs/daily_$(date +\%Y\%m\%d).log 2>&1

# 11:00 - 上午收盘前扫描
0 11 * * 1-5 cd /root/.openclaw/workspace/quant-trading && python3 auto_trading.py --once >> logs/daily_$(date +\%Y\%m\%d).log 2>&1

# 13:05 - 下午开盘扫描
5 13 * * 1-5 cd /root/.openclaw/workspace/quant-trading && python3 auto_trading.py --once >> logs/daily_$(date +\%Y\%m\%d).log 2>&1

# 14:00 - 午后扫描
0 14 * * 1-5 cd /root/.openclaw/workspace/quant-trading && python3 auto_trading.py --once >> logs/daily_$(date +\%Y\%m\%d).log 2>&1

# 14:30 - 尾盘扫描 (重点)
30 14 * * 1-5 cd /root/.openclaw/workspace/quant-trading && python3 auto_trading.py --once >> logs/daily_$(date +\%Y\%m\%d).log 2>&1

# 14:50 - 尾盘买入机会 (重点)
50 14 * * 1-5 cd /root/.openclaw/workspace/quant-trading && python3 auto_trading.py --tail >> logs/daily_$(date +\%Y\%m\%d).log 2>&1

# 15:30 - 收盘报告
30 15 * * 1-5 cd /root/.openclaw/workspace/quant-trading && python3 -c "from paper_trading import PaperTrading; p = PaperTrading(); p.print_report()" >> logs/daily_$(date +\%Y\%m\%d).log 2>&1

# 20:00 - 晚间复盘 (每日)
0 20 * * 1-5 cd /root/.openclaw/workspace/quant-trading && python3 main.py --review >> logs/daily_$(date +\%Y\%m\%d).log 2>&1

# 每周日 22:00 - 周度复盘 (仅周日)
0 22 * * 0 cd /root/.openclaw/workspace/quant-trading && python3 -c "from paper_trading import PaperTrading; p = PaperTrading(); p.print_report()" >> logs/weekly_$(date +\%Y\%m\%d).log 2>&1
EOF

# 安装 crontab
echo "安装新的 crontab 任务..."
crontab /tmp/quant_cron.txt

# 验证
echo ""
echo "✅ crontab 设置完成！"
echo ""
echo "当前 crontab 任务:"
echo "============================================================"
crontab -l
echo "============================================================"
echo ""
echo "📋 定时任务说明:"
echo "  09:20 - 早盘监控启动"
echo "  09:35 - 早盘第一次扫描"
echo "  10:00 - 早盘第二次扫描"
echo "  10:30 - 早盘第三次扫描"
echo "  11:00 - 上午收盘前扫描"
echo "  13:05 - 下午开盘扫描"
echo "  14:00 - 午后扫描"
echo "  14:30 - 尾盘扫描 (重点)"
echo "  14:50 - 尾盘买入 (重点)"
echo "  15:30 - 收盘报告"
echo "  20:00 - 晚间复盘"
echo "  周日 22:00 - 周度复盘"
echo ""
echo "📁 日志文件：$LOG_DIR/daily_YYYYMMDD.log"
echo ""
echo "✅ 系统已设置为自动运行！"
echo "   下个交易日：2026-03-09 (周一) 09:20"
echo ""

# 清理临时文件
rm -f /tmp/quant_cron.txt
